name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  DAY_OF_WEEK: Monday
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "The secret variable ${{secrets.KEY}}"
      - run: echo "The environment variable ${{env}}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Say Hello Mona it's Monday
        run: echo "$DAY_OF_WEEK"
      - run: echo "🍏 This job's status is ${{ job.status }}."
